eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8088

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: token
          uri: lb://token
          predicates:
            - Path=/auth/**

        - id: user-management
          uri: lb://user-management
          predicates:
            - Path=/users/**
          filters:
            - UserManagementFilter

        - id: selling
          uri: lb://selling
          predicates:
            - Path=/selling/**, /campaign/**, /product-modify/**
          filters:
            - SellingFilter

        - id: report
          uri: lb://report
          predicates:
            - Path=/sales/**
          filters:
            - ReportFilter

        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**
      discovery:
        locator:
          enabled: true

