eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

server:
  port: 8088

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authorization
          uri: lb://authorization
          predicates:
            - Path=/auth/**

        - id: user-management
          uri: lb://user-management
          predicates:
            - Path=/users/**
          filters:
            - UserManagementFilter

        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**
      discovery:
        locator:
          enabled: true

