eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 8090
spring:
  application:
    name: token
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marketdb
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
